name: Pylint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install graphviper
      run: |
        pip install graphviper
    - name: Install hvplot
      run: |
        pip install hvplot
    - name: Create dummy version file
      run: |
        touch vidavis/__version__.py
        echo "__version__ = '0.0.0'" >> vidavis/__version__.py
    - name: Analysing the code with pylint
      run: |
        pylint "--msg-template='{abspath}:{line:5d},{column:2d}: {msg} ({symbol})'" --rcfile=pylintrc --output-format=colorized $(git ls-files '*.py' | egrep '^src/vidavis/')
